# Data Manipulation notebook

Test implementation of data manipulation techniques

In [1]:
%load_ext autoreload
%autoreload 2

Imports

In [2]:
import pandas as pd
import os
from data_manipulation_methods import *

Load data

In [3]:
df = getDF(os.path.join('data', 'Clothing_Shoes_and_Jewelry_5.json.gz'), max_lines=1e3)
df.head()

,overall,vote,verified,reviewTime,reviewerID,asin,style,reviewerName,reviewText,summary,unixReviewTime,image
0,5.0,2,True,"05 4, 2014",A2IC3NZN488KWK,0871167042,{'Format:': ' Paperback'},Ruby Tulip,"This book has beautiful photos, good and under...",Unique designs,1399161600,NaN
1,5.0,0,True,"03 31, 2014",A30FG02C424EJ5,0871167042,{'Format:': ' Paperback'},NWCancerBaby,Loved their approach in this book and that it ...,Great Book,1396224000,NaN
2,5.0,0,True,"05 30, 2015",A2G9GWQEWWNQUB,0871167042,{'Format:': ' Paperback'},Pamelarenee,great,Five Stars,1432944000,NaN
3,5.0,0,True,"02 21, 2015",A3NI5OGW35SLY2,0871167042,{'Format:': ' Paperback'},Gail,"Always love the way Eva thinks, and there are ...",Great Book!,1424476800,NaN
4,5.0,0,True,"01 21, 2015",A1OPRA4NE56EV6,0871167042,{'Format:': ' Paperback'},carol a inman,Nice patterns,Five Stars,1421798400,NaN

Synthetic spurious counterfactuals methods

In [4]:
for i,text in enumerate(df['reviewText']):
    print(text)
    if i > 5: break

This book has beautiful photos, good and understandable directions, and many different kinds of jewelry.  Wire working and metalsmithing jewelry are covered.  Highly recommend this book.
Loved their approach in this book and that it was a "paperback".  Easy to use and inspiring me to use up my beachcombing finds.
great
Always love the way Eva thinks, and there are some fun designs in this book. Easy to advanced for all. Fast shipping.
Nice patterns
love the spirit of the book and some of the projects.
Not a fan. Limited designs. Limited content for the money

In [5]:
label_Y(df)
df.head()

,overall,vote,verified,reviewTime,reviewerID,asin,style,reviewerName,reviewText,summary,unixReviewTime,image,above3Stars
0,5.0,2,True,"05 4, 2014",A2IC3NZN488KWK,0871167042,{'Format:': ' Paperback'},Ruby Tulip,"This book has beautiful photos, good and under...",Unique designs,1399161600,NaN,True
1,5.0,0,True,"03 31, 2014",A30FG02C424EJ5,0871167042,{'Format:': ' Paperback'},NWCancerBaby,Loved their approach in this book and that it ...,Great Book,1396224000,NaN,True
2,5.0,0,True,"05 30, 2015",A2G9GWQEWWNQUB,0871167042,{'Format:': ' Paperback'},Pamelarenee,great,Five Stars,1432944000,NaN,True
3,5.0,0,True,"02 21, 2015",A3NI5OGW35SLY2,0871167042,{'Format:': ' Paperback'},Gail,"Always love the way Eva thinks, and there are ...",Great Book!,1424476800,NaN,True
4,5.0,0,True,"01 21, 2015",A1OPRA4NE56EV6,0871167042,{'Format:': ' Paperback'},carol a inman,Nice patterns,Five Stars,1421798400,NaN,True

In [6]:
generate_synthetic_text(df)
df.head()

,overall,vote,verified,reviewTime,reviewerID,asin,style,reviewerName,reviewText,summary,unixReviewTime,image,above3Stars,perturbType,perturbedText,counterFactText
0,5.0,2,True,"05 4, 2014",A2IC3NZN488KWK,0871167042,{'Format:': ' Paperback'},Ruby Tulip,"This book has beautiful photos, good and under...",Unique designs,1399161600,NaN,True,1,"This book has beautiful photos, good and under...","This book has beautiful photos, good and under..."
1,5.0,0,True,"03 31, 2014",A30FG02C424EJ5,0871167042,{'Format:': ' Paperback'},NWCancerBaby,Loved their approach in this book and that it ...,Great Book,1396224000,NaN,True,0,Loved their approach in this book and that it ...,Loved their approach in this book and that it ...
2,5.0,0,True,"05 30, 2015",A2G9GWQEWWNQUB,0871167042,{'Format:': ' Paperback'},Pamelarenee,great,Five Stars,1432944000,NaN,True,0,great,great
3,5.0,0,True,"02 21, 2015",A3NI5OGW35SLY2,0871167042,{'Format:': ' Paperback'},Gail,"Always love the way Eva thinks, and there are ...",Great Book!,1424476800,NaN,True,1,"Always love thezzzzz way Eva thinks, and there...","Always love thexxxxx way Eva thinks, and there..."
4,5.0,0,True,"01 21, 2015",A1OPRA4NE56EV6,0871167042,{'Format:': ' Paperback'},carol a inman,Nice patterns,Five Stars,1421798400,NaN,True,1,Nice patterns,Nice patterns

In [7]:
subsample_data(df)
N_Z1 = df['above3Stars'].sum()
N_Y1_Z1 = (df['above3Stars'] & (df['syntheticType']==1)).sum()
P_Y1_Z1 = N_Y1_Z1 / N_Z1
N_Z0 = (~df['above3Stars']).sum()
N_Y0_Z0 = ((~df['above3Stars']) & (df['syntheticType']==0)).sum()
P_Y0_Z0 = N_Y0_Z0 / N_Z0
print("N_Z", N_Z1,N_Z0)
print("N_Z_Y", N_Y1_Z1, N_Y0_Z0)
print("p",P_Y1_Z1, P_Y0_Z0)

N_Z 187 187
N_Z_Y 56 56
p 0.2994652406417112 0.2994652406417112

In [8]:
train_df, test_df = split_dataset(df)

N_Z1 = train_df['above3Stars'].sum()
N_Y1_Z1 = (train_df['above3Stars'] & (train_df['syntheticType']==1)).sum()
P_Y1_Z1 = N_Y1_Z1 / N_Z1
N_Z0 = (~train_df['above3Stars']).sum()
N_Y0_Z0 = ((~train_df['above3Stars']) & (train_df['syntheticType']==0)).sum()
P_Y0_Z0 = N_Y0_Z0 / N_Z0
print("N_Z", N_Z1,N_Z0)
print("N_Z_Y", N_Y1_Z1, N_Y0_Z0)
print("p",P_Y1_Z1, P_Y0_Z0)

N_Z 148 151
N_Z_Y 47 44
p 0.31756756756756754 0.2913907284768212

In [9]:
drop_data(df)
N_Z1 = df['above3Stars'].sum()
N_V_Z1 = (df['above3Stars'] & df['vote']>0).sum()
P_V_Z1 = N_V_Z1 / N_Z1
N_Z0 = (~df['above3Stars']).sum()
N_V_Z0 = (~df['above3Stars'] & df['vote']>0).sum()
P_V_Z0 = N_V_Z0 / N_Z0
print(P_V_Z1, P_V_Z0)

0.8846153846153846 0.782608695652174